spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/opc-ua
    username: sa
    password:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    dynamic: true
#  config:
#    activate:
#      on-profile: local

logging:
  level:
    com: INFO

opc-ua:
  host: opcuaserver.com
  port: 48010
  pool-size : 3