spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/opc-ua
    username: sa
    password:
  profiles:
    active: local
  rabbitmq:
    port: 5672
    host: 192.168.0.9
    username: guest
    password: guest
    dynamic: true
#  config:
#    activate:
#      on-profile: local



logging:
  level:
    com: info

opc-ua:
  host: opcuaserver.com
  port: 48010